language: perl
perl:
  - "5.18.2"
addons:
  apt:
    packages:
      - bash
sudo: false
script:
  - prove -lv $(test-dirs)
branches:
  except:
    - /^wip\//
    - /^dev/
    - /^app/
    - /^blocked/
notifications:
  email: false
