.TH AbleApp 1
.SH NAME
abl \- manage projects with agile devops
.SH SYNOPSIS
.B abl
\fB\ command \fR
[\fB\ paramenter \fR]
[\fB\ -o options \fR]
.SH DESCRIPTION
.BR create
Create a new project.
.PP 
.B setup
Setup a project, interactivelly, step by step.
.PP 
.B info
Show all info about a project.
.PP 
.B run
Run a bot.
.PP 
.B stop
Kill a bot running.
.SH OPTIONS
.TP
.BR \-n ", " \-\-bits =\fIBITS\fR
Set the number of bits to modify.
Default is one bit.
.SH SEE ALSO
git(1), task(1) 
.SH BUGS
If you know some bug, just email it to hi@kobkob.org
.SH AUTHOR
Monsenhor (filipo@kobkob.org)
.Dd   March 26, 2018
.Dt   ABLEAPP [1] [1]
.Os   LINUX [ubuntu/17.10]

