---
abstract: 'The agile DevOps manager'
author:
  - 'Monsenhor <monsenhor@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Able
requires:
  Carp: '0'
  Config::YAML: '0'
  Data::Dumper: '0'
  Data::Section: '0'
  File::Copy: '0'
  File::Spec: '0'
  Getopt::Long: '0'
  Git::Repository: '0'
  GitLab::API::v4: '0.13'
  Mojolicious: '0'
  Term::ANSIColor: '4.00'
  Term::UI: '0'
  Test::More: '0'
version: '0.001'
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.70'
