BEGIN TRANSACTION;
CREATE TABLE "Verification" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`projid`	INTEGER NOT NULL
);
CREATE TABLE "Release" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`projid`	INTEGER NOT NULL
);
CREATE TABLE "Project" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`buid`	INTEGER NOT NULL
);
CREATE TABLE "Plan" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`projid`	INTEGER NOT NULL
);
CREATE TABLE "Package" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`projid`	INTEGER NOT NULL
);
CREATE TABLE "Monitor" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`projid`	INTEGER NOT NULL
);
CREATE TABLE Domain (
  id long int NOT NULL ,
  name string NOT NULL ,
  id_bus long int NOT NULL 
);
CREATE TABLE "Creation" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`projid`	INTEGER NOT NULL
);
CREATE TABLE "Configuration" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`projid`	INTEGER NOT NULL,
	`mgrid`	INTEGER NOT NULL,
	`url`	TEXT,
	`description`	TEXT
);
CREATE TABLE "BussinessUnit" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL
);
COMMIT;
